Script started on 2017年03月18日 (週六) 20時34分18秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m whoamo[Ku[Ki; pwd
pd2vm
/home/pd2vm
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git congi[K[Kfig -l
user.name=moonlightpwr
user.email=ssss6522@gmail.com
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git clone gttps:[K[K[K[K[K[Khrrp[K[K[K[Kttp[K[K[Khttps://githun[Kb.com/moonlightpwe[Kr/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
Checking connectivity... done.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m 
Script done on 2017年03月18日 (週六) 20時35分16秒
